---
- name: Download InfluxDB GPG key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
  become: yes

- name: Ensure apt-transport-https is installed
  apt:
    name: apt-transport-https
    state: present
  become: yes

- name: Configure InfluxDB APT repository
  apt_repository:
    repo: 'deb https://repos.influxdata.com/ubuntu {{ ansible_distribution_release }} stable'
    state: present
  become: yes
