---
- include: add_influx_repo.yml

- name: Install InfluxDB packages
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - "{{ influxdb_packages }}"
  become: yes
